a = input('Digite algo: ')

print('O tipi primitivo de {} é '.format(a), type(a))
print('({}) Só tem espaços?'.format(a), a.isspace())
print('({}) É um número?'.format(a),a.isnumeric())
print('({}) É alfabetico?'.format(a), a.isalpha())
print('({}) É alfa numerico?'.format(a), a.isalnum())
print('({}) Esta em maiusculas?'.format(a), a.isupper())
print('({}) Esta em minusculas?'.format(a), a.islower())
print('({}) Esta capitalizado?'.format(a), a.istitle())
